### ISSUE TITLE
IPCAM as QRCode Scanner

### ISSUE THREAD

**Issue by ricardojlrufino** [dlbeer/quirc#104]
Just sharing a project that uses that library.
I turned an IP camera (which runs Linux) into a QRCODE Reader this is the result:
https://youtu.be/o10Hf9vFvKs

https://github.com/ricardojlrufino/yicam_qrcode

congratulations to the creators of the libary, the performance was very good

**Comment by dlbeer** [comment]
On Tue, Apr 13, 2021 at 08:58:55AM -0700, Ricardo JL Rufino wrote:
> Just sharing a project that uses that library.
> I turned an IP camera (which runs Linux) into a QRCODE Reader this is the result:
> https://youtu.be/o10Hf9vFvKs
> 
> https://github.com/ricardojlrufino/yicam_qrcode
> 
> congratulations to the creators of the libary, the performance was very good

Nice work! Glad to hear that the library was useful to you.

-- 
Daniel Beer ***@***.***> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B
