### ISSUE TITLE
quirc_decode returns 0 but payload is invalid

### ISSUE THREAD

**Issue by Jimmy-Z** [dlbeer/quirc#19]
extracted code from quirc_extract looks fine, quirc_decode returns 0 but data_type = 0, payload_len = 0

![ZXing generated QR Code](https://zxing.org/w/chart?cht=qr&chs=350x350&chld=L&choe=UTF-8&chl=test)

**Comment by dlbeer** [comment]
I've just pushed a fix for this. Pull the latest version and give it another try.

**Comment by Jimmy-Z** [comment]
nice, it works now
