### ISSUE TITLE
Possible problem in thresholding

### ISSUE THREAD

**Issue by nuxeh** [dlbeer/quirc#23]
Hi,

I've been testing quirc using a number of ways of degrading QR codes to see how it performs.

I found this case, where i think there might be an issue with the thresholding:

Works:

![image](https://cloud.githubusercontent.com/assets/1516017/22343563/79f7d272-e3f0-11e6-9449-24a87d4e8181.png)

Fails:

![image](https://cloud.githubusercontent.com/assets/1516017/22343488/2ba9b8f6-e3f0-11e6-9cee-e368b9ddf9ba.png)

The central grey areas have the same contrast, i think this could be a problem with the big difference in contrast in the white border making the row averaging unreliable.

Any ideas how to improve this?

Ed

**Comment by cfreundlich** [comment]
Have you tried "adaptive thresholding?"  See http://docs.opencv.org/3.2.0/d7/d4d/tutorial_py_thresholding.html

**Comment by dlbeer** [comment]
On Thu, Jan 26, 2017 at 09:56:01AM -0800, nuxeh wrote:
> Hi,
> 
> I've been testing quirc using a number of ways of degrading QR codes to see how it performs.
> 
> I found this case, where i think there might be an issue with the thresholding:
> 
> Works:
> 
> ![image](https://cloud.githubusercontent.com/assets/1516017/22343563/79f7d272-e3f0-11e6-9449-24a87d4e8181.png)
> 
> Fails:
> 
> ![image](https://cloud.githubusercontent.com/assets/1516017/22343488/2ba9b8f6-e3f0-11e6-9cee-e368b9ddf9ba.png)
> 
> The central grey areas have the same contrast, i think this could be a problem with the big difference in contrast in the white border making the row averaging unreliable.

Yes, it could well be.

The current thresholding algorithm probably isn't the best, but it does
run in linear time without much additional memory.

Unfortunately I don't have any ideas to improve it right now, but if you
wanted to try something new and better, I'd be happy to consider
patches!

Perhaps Otsu's method in the OpenCV link above might be worth a try.

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by cfreundlich** [comment]
Otsu will probably not improve your result.  It will use the same threshold for the whole image.  Try adaptive thresholding, which changes for different areas  of the image.

**Comment by kwagyeman** [comment]
https://github.com/openmv/apriltag/blob/master/apriltag_quad_thresh.c#L1167

**Comment by kAworu** [comment]
@nuxeh Otsu's algorithm has been implemented in #55, is it of any help for your case?

**Comment by nuxeh** [comment]
Ah, very nice... I did implement otsu thresholding myself when I was originally working on this and it worked very well... I neglected to update this issue, or push anything upstream, though.

**Comment by kAworu** [comment]
Alright, closing this one then :)
