### ISSUE TITLE
[Question] Interested in CMake?

### ISSUE THREAD

**Issue by p-groarke** [dlbeer/quirc#26]
Hello, first off thanks for quirc :)

I am working in a somewhat unique build environment. I will pushing a cmake branch to my fork soon, and I would like to know if you are interested by it? A build system is usually a very subjective and personal subject, I fully understand if you do not want a PR for this.

Reasons I needed cmake include compiling on windows. Cmake automagically generates VS projects. VS2015 doesn't support C99 and C11, but they have added the LLVM toolchain. So by issuing `cmake .. -G "Visual Studio 14 2015 Win64" -T "LLVM-vs2014"` you can generate a Visual Studio project that compiles fine. I now have a windows lib (yay!).

If you are at all interested, I could spend the time to add cmake installation steps, so other users could use the builtin find_package(quirc) cmake function.

Good day

**Comment by dlbeer** [comment]
Being able to build easily on Windows would be a big plus, but is it possible to do this in a way that means that the old-style Makefile can still be used for those who don't have or don't want to install CMake?

**Comment by sagartesla** [comment]
I made few syntax changes and now able to build it on my Visual Studio 10. But, Now I don't know how should i load a image using ? Do i need to use opencv for it ?

**Comment by dlbeer** [comment]
On Fri, Jul 07, 2017 at 10:12:48AM +0000, sagartesla wrote:
> I made few syntax changes and now able to build it on my Visual Studio
> 10. But, Now I don't know how should i load a image using ? Do i need
> to use opencv for it ?

You could try jpeglib or libpng. There is code to use these libraries
already included in the test/demo programs.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by aruiz** [comment]
I'd strongly recommend using meson, it supports Windows and VS, and it has a nice dependency management system called wrap that you can use to consume modules already ported to meson listed in https://wrapdb.mesonbuild.com/:
http://mesonbuild.com/Wrap-dependency-system-manual.html

It does not rely on generating Makefiles and it uses ninja underneath so it is blazing fast.

You can wrap it with a Makefile to keep things building of couse.
