### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by mjbshaw** [dlbeer/quirc#27]
I've got a patch to add quirc to [Homebrew](https://brew.sh/), but they really like to avoid having libraries that have no tagged releases.

Would it be possible to tag a release for quirc? Even if it's just a simple version string like 0.1 or 0.0.1.

**Comment by kAworu** [comment]
I would suggest 1.0 to match the `LIB_VERSION` from `Makefile`, see https://github.com/dlbeer/quirc/blob/master/Makefile#L21.

**Comment by dlbeer** [comment]
Done. v1.0 it is.
