### ISSUE TITLE
[Question]A memory leak?

### ISSUE THREAD

**Issue by Lak4CYUT** [dlbeer/quirc#32]
Hi, 
Thanks for your library first, it helps me a lot.

In normal case, this library should work on below steps,
1. quirc_new()
2. quirc_resize()
3. quirc_begin(), quirc_end()
4. quirc_count, LOOP [quirc_extract(), quirc_decode()]
5. Goto 3 or 6
6. quirc_destroy()

Is it right?

When first time call quirc_resize(), it will allocates a memory for q->pixels. 
But in quirc_end() -> pixels_setup(), it has a chance be replace with q->image without release.

> (q->pixels = (quirc_pixel_t *)q->image;)

I think that may cause a memory leak, but I am not sure, so I come to here and try to report it to you.

Anyway, thanks for your project.

**Comment by dlbeer** [comment]
No, that's not a leak -- the assignment to q->pixels only happens in the case where quirc_pixel_t is configured to be an 8-bit type. In that case, there is only one memory allocation, which q->pixels and q->image both point to.

However, in the course of investigating this, I did find a leak in quirc_resize (which I've now fixed)!

**Comment by Lak4CYUT** [comment]
Cool!
You are right, thanks.
