### ISSUE TITLE
can scan qrcode from a picture?how?

### ISSUE THREAD

**Issue by ziling9527** [dlbeer/quirc#33]
I have a rgb picture,this lib can scan qrcode from picture and how?thanks

**Comment by dlbeer** [comment]
On Thu, May 18, 2017 at 10:09:24PM -0700, ziling9527 wrote:
> I have a rgb picture,this lib can scan qrcode from picture and how?thanks

Yes, it can. Check the README file in the repository for an overview and
an example of its use.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B
