### ISSUE TITLE
quirc can't decode a qrcode 

### ISSUE THREAD

**Issue by paolostivanin** [dlbeer/quirc#43]
Hello,
I'm implementing a small qrcode parser function based [on this function](https://github.com/dlbeer/quirc/blob/master/tests/qrtest.c#L82) but I can't parse on of the test image I have.
The first image is correctly parsed, but the second it's not.

![test1](https://user-images.githubusercontent.com/1040943/37272168-23273ba8-25d6-11e8-99c5-04029068b7fe.png)

![test2](https://user-images.githubusercontent.com/1040943/37272167-2310cf58-25d6-11e8-8aa6-0514bd38827d.png)

```
$ qrtest ../test1.png
quirc test program
Copyright (C) 2010-2012 Daniel Beer <dlbeer@gmail.com>
Library version: 1.0

                                          Time (ms)       Count
  Filename                         Load    ID Total    ID   Dec
-------------------------------------------------------------------------------
  test1.png                     :     1     3     4     1     1

$ qrtest ../test2.png
quirc test program
Copyright (C) 2010-2012 Daniel Beer <dlbeer@gmail.com>
Library version: 1.0

                                          Time (ms)       Count
  Filename                         Load    ID Total    ID   Dec
-------------------------------------------------------------------------------
  test2.png                     :     0     1     1     0     0
```

I have tried with `zbarimg` and both are correctly parsed, so it doesn't seem to be an issue with the 2nd image.

I tried on Fedora 27 x64, using latest master.

**Comment by dlbeer** [comment]
On Mon, Mar 12, 2018 at 08:19:22AM +0000, Paolo Stivanin wrote:
> Hello,
> I'm implementing a small qrcode parser function based [on this function](https://github.com/dlbeer/quirc/blob/master/tests/qrtest.c#L82) but I can't parse on of the test image I have.
> The first image is correctly parsed, but the second is not.
> 
> ![test1](https://user-images.githubusercontent.com/1040943/37272168-23273ba8-25d6-11e8-99c5-04029068b7fe.png)
> 
> ![test2](https://user-images.githubusercontent.com/1040943/37272167-2310cf58-25d6-11e8-8aa6-0514bd38827d.png)
> 
> ```
> $ qrtest ../test1.png
> quirc test program
> Copyright (C) 2010-2012 Daniel Beer <dlbeer@gmail.com>
> Library version: 1.0
> 
>                                           Time (ms)       Count
>   Filename                         Load    ID Total    ID   Dec
> -------------------------------------------------------------------------------
>   test1.png                     :     1     3     4     1     1
> 
> $ qrtest ../test2.png
> quirc test program
> Copyright (C) 2010-2012 Daniel Beer <dlbeer@gmail.com>
> Library version: 1.0
> 
>                                           Time (ms)       Count
>   Filename                         Load    ID Total    ID   Dec
> -------------------------------------------------------------------------------
>   test2.png                     :     0     1     1     0     0
> ```
> 
> I have tried with `zbarimg` and both are correctly parsed, so it doesn't seem to be an issue with the 2nd image.
> 
> I tried on Fedora 27 x64, using latest master.

Hi Paolo,

The second image is not valid, as it doesn't have the mandatory quiet
zone (white border). If you this, it decodes correctly with the latest
master.

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by paolostivanin** [comment]
Hello,
thanks for the answer. Problem is that the user gets the image from a website and then pass it to my software, so I am not really in control of how the image is generated.

**Comment by dlbeer** [comment]
On Mon, Mar 12, 2018 at 12:23:32PM -0700, Paolo Stivanin wrote:
> Hello,
> thanks for the answer. Problem is that the user gets the image from a website and then pass it to my software, so I am not really in control of how the image is generated.

Couldn't you just add a white border to every image you're given? It
will do no harm when the code is already valid.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by paolostivanin** [comment]
Yup, good idea. I guess I can do it with libpng when I am filling the buffer, right?

**Comment by dlbeer** [comment]
On Tue, Mar 13, 2018 at 11:32:35AM +0000, Paolo Stivanin wrote:
> Yup, good idea. I guess I can do it with libpng when I am filling the buffer, right?

Yes, you can just copy your image into the middle of a larger buffer and
fill the outside with white pixels. You don't need to do anything
special with libpng.

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by paolostivanin** [comment]
one last question, unrelated to the issue: do you plan to expose some sort of camerar api? This would be quite handy :)

Thanks

**Comment by dlbeer** [comment]
On Tue, Mar 13, 2018 at 09:01:12PM +0000, Paolo Stivanin wrote:
> one last question, unrelated to the issue: do you plan to expose some sort of camerar api? This would be quite handy :)

No, there are already a whole lot of camera APIs and libraries that
already exist. If you're looking for an example for Linux, the quirc
demo program uses V4L2.

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B
