### ISSUE TITLE
Quirc for video files?

### ISSUE THREAD

**Issue by geaplanet** [dlbeer/quirc#46]
Hi, I'm looking for a program that is capable of finding qr codes within a video file. Can Quirc do this?

Thanks.

**Comment by dlbeer** [comment]
On Sun, Sep 02, 2018 at 03:01:51PM -0700, geaplanet wrote:
> Hi, I'm looking for a program that is capable of finding qr codes within a video file. Can Quirc do this?

Yes, that should be possible. Just extract the frames and feed them one
by one to quirc.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B
