### ISSUE TITLE
QUIRC_ERROR_DATA_ECC on each Image

### ISSUE THREAD

**Issue by YazanBawab** [dlbeer/quirc#47]
when ever i feed an image to the quirc decoder it return an QUIRC_ERROR_DATA_ECC Error i have checked the bar-codes and they are readable.

can you help me what i am messing? I have followed the implementation as described in the read me file

**Comment by kAworu** [comment]
Hi @YazanBawab ,

Could you please provide the image so that it's easier to duplicate the problem? Without a file triggering the error it's nearly impossible to debug this I guess.

Best regards,
Alex

**Comment by YazanBawab** [comment]
Hi @kAworu ,
sure, but I have converted the image to 8Bit BMP image using mspaint cause i read that the image must be 8 bit(GrayScale).
(couldn't upload the converted image "Security issue i think").
![frame 1](https://user-images.githubusercontent.com/37582440/44985500-4357ad80-af89-11e8-9d98-b46e69caa1dd.png)

thanks for the support.
Yazan

**Comment by dlbeer** [comment]
On Mon, Sep 03, 2018 at 04:56:26AM -0700, YazanBawab wrote:
> Hi @kAworu ,
> sure, but I have converted the image to 8Bit BMP image using mspaint cause i read that the image must be 8 bit(GrayScale).
> (couldn't upload the converted image "Security issue i think").
> ![frame 1](https://user-images.githubusercontent.com/37582440/44985500-4357ad80-af89-11e8-9d98-b46e69caa1dd.png)
> 
> thanks for the support.
> Yazan

Hi Yazan,

That image seems to decode just fine using the "inspect" tool. Have you
had a look at the source code for this tool in the quirc repository? Are
you sure you're loading your image into the buffer correctly?

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by dlbeer** [comment]
On Mon, Sep 03, 2018 at 11:24:20PM -0700, YazanBawab wrote:
> if (bmp->LockBits(&rectLockedBmpData, ImageLockModeRead | ImageLockModeWrite, PixelFormat8bppIndexed, &BmpData) != ::Ok)

You need grayscale data, not palettized (PixelFormat...Indexed).

> INT stride = BmpData.Stride;
> 
> BYTE *p = (BYTE *)(VOID*)BmpData.Scan0;
> 
> INT index = 0;
> for (INT y = 0; y < width; y++)
> {
> for (INT x = 0; x <height; x++)
> {
> bytes[index] = (BYTE)p[(x)* stride + (y)];
> index++;
> }
> }

This is unlikely to be correct. Assuming the data is in row-major order,
you're transposing it when copying into bytes (you probably want to
multiply stride by y, not x).

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by YazanBawab** [comment]
Daniel thanks for the hints,

finally i found what was the cause i was reading the image column by column and but it in the buffer, after reading it in row by row it worked fine with me.

```
INT index = 0;
 for (INT y = 0; y < height; y++)
 {
 for (INT x = 0; x <width; x++)
 {
 bytes[index] = (BYTE)p[(y)* stride + (x)];
 index++;
 }
 }
```

thanks guyz for helping :)

**Comment by YazanBawab** [comment]
Daniel I have loaded an (1479*704) gray scale bitmap Image with a QR bar-code Included in it but the count stay zero.

is their any parameter should be changed to read large images and detect bar-codes??

(the Image)
![image 1](https://user-images.githubusercontent.com/37582440/45027808-24215480-b04b-11e8-905a-ec343618cbd9.jpg)

**Comment by YazanBawab** [comment]
Hello Daniel,

Are you sure that this is the issue!! cause i have added the same barcode to the image (not mirrored) and it didn't find it, the `quirc_count(qr)` keep returning zero(0) 

(the new Image with the barcode)
![image 1 1](https://user-images.githubusercontent.com/37582440/45071529-61cfbd00-b0df-11e8-9bb8-e1b4977351aa.jpg)


Regards,
Yazan Bawab

**Comment by dlbeer** [comment]
That's still mirrored. You have just rotated it 180 degrees, but it's still
back to front.

**Comment by YazanBawab** [comment]
Alright Daniel, I have made some more testing scenarios to diagnosis the problem i want to discuse them with you cause i couldn't reach any point with this invistigation.

First Testing Scenario:
Blank Image Size(1480*706) with an Anticlockwise 90 degrees rotated QR barcode.
(Image)
![withbarcodecopiedccw90](https://user-images.githubusercontent.com/37582440/45079410-30fd8100-b0fb-11e8-926b-227dced4c534.jpg)
(QR barcode)
![barcodeascheque](https://user-images.githubusercontent.com/37582440/45079441-3d81d980-b0fb-11e8-8388-66cb2d128a41.jpg)
(Anticlockwise 90 degrees rotated QR barcode)
![barcodeaschequeccw90](https://user-images.githubusercontent.com/37582440/45079466-4f637c80-b0fb-11e8-8c73-054e500b6ba6.jpg)

Result:
the engine successfully read the barcode and return the data.

Second Testing Scenario:
Blank Image Size(1480*706) with a non rotated QR barcode.
(Image)
![withbarcodecopied](https://user-images.githubusercontent.com/37582440/45079596-a9644200-b0fb-11e8-9062-8e8e8d888345.jpg)
(QR barcode)
![barcodeascheque](https://user-images.githubusercontent.com/37582440/45079610-b2551380-b0fb-11e8-85ed-b01eb32dcb02.jpg)

Result:
the engine successfully read the barcode and return data.

Third Testing Scenario:
Cheque template image Size(1480*706) with an Anticlockwise 90 degrees rotated QR barcode
(Image)
![image 1](https://user-images.githubusercontent.com/37582440/45079750-f8aa7280-b0fb-11e8-91c4-2173430ea246.jpg)
(Anticlockwise 90 degrees rotated QR barcode)
![barcodeaschequeccw90](https://user-images.githubusercontent.com/37582440/45079767-03fd9e00-b0fc-11e8-865d-2fdcab443acd.jpg)
(QR barcode)
![barcodeascheque](https://user-images.githubusercontent.com/37582440/45079785-0eb83300-b0fc-11e8-9d4c-f5aa58a99bf4.jpg)
Result:
no QR barcode was detected from the engine.(failed scenario).

Please advise what could be the cause of this issue?? could it be cause of the background of the Third Image ?? Does the engine use some Binarization algorithm or any image processing!!!

Regards,
Yazan Bawab

**Comment by YazanBawab** [comment]
thanks for the support mate :)
