### ISSUE TITLE
Out of bounds read in quirc_strerror

### ISSUE THREAD

**Issue by snake66** [dlbeer/quirc#5]
There's a off-by one error which can cause quirc_strerror to do an out of bounds read, changing the `<=` to `<` in the test should fix the issue:

```diff
diff --git a/functional/libquirc/lib/quirc.c b/functional/libquirc/lib/quirc.c
index 9abbc6c..e0ffef4 100644
--- a/functional/libquirc/lib/quirc.c
+++ b/functional/libquirc/lib/quirc.c
@@ -74,7 +74,7 @@ static const char *const error_table[] = {
 
 const char *quirc_strerror(quirc_decode_error_t err)
 {
-    if (err >= 0 && err <= sizeof(error_table) / sizeof(error_table[0]))
+    if (err >= 0 && err < sizeof(error_table) / sizeof(error_table[0]))
         return error_table[err];
 
     return "Unknown error";
```

**Comment by bidafiwoc** [comment]
Just started examining quirc, and I note that this patch was replied to (@dlbeer above) and supposedly queued to be applied, but not actually reflected in current source code.  Status, please?  Thanks.

**Comment by dlbeer** [comment]
It was applied in February 2013:

https://github.com/dlbeer/quirc/commit/c8b1861b8ff066a019f0c63c7cafa5d710e75672

I replied via email, and so didn't close the issue on the web interface.

**Comment by bidafiwoc** [comment]
@dlbeer: Thanks for updating issue db.
