### ISSUE TITLE
DECODE FAILED: ECC failure

### ISSUE THREAD

**Issue by ercjethava** [dlbeer/quirc#52]
I am decoding qr code using quirc library and getting this message.DECODE FAILED: ECC failure what does that mean.The same qr-code I am able to decode using another library.

**Comment by dlbeer** [comment]
ercjethava <notifications@github.com> writes:
>    I am decoding qr code using quirc library and getting this message.DECODE
>    FAILED: ECC failure what does that mean.The same qr-code I am able to
>    decode using another library.

If it's a valid QR code, that likely means that the code cells have been
incorrectly read and the library can't correct the errors.

Have you tried looking at the image using the included "inspect" tool to
see if the sampling grid is ok?

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by ercjethava** [comment]
what kind of inspect tool ?

**Comment by dlbeer** [comment]
ercjethava <notifications@github.com> writes:
>    what kind of inspect tool ?

There is a tool included in the source repository called "inspect". Give
it an image and it will pop up an SDL window showing what quirc has
detected and how it's reading the grid.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by ercjethava** [comment]
yes that tools displays grid view of qr code and at bottom it says Decoding FAILED: ECC failure. BTW thats nice tool(inspect).

**Comment by dlbeer** [comment]
ercjethava <notifications@github.com> writes:
>    yes that tools displays grid view of qr code and at bottom it says
>    Decoding FAILED: ECC failure. BTW thats nice tool(inspect).

Could you send me (dlbeer@gmail.com) the image or post it here?

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by ercjethava** [comment]
OK I got it.I took screenshot of qr code from pdf  so it not detected its properly .Now it works fine.I tool screenshot again from pdf.thanks
