### ISSUE TITLE
Compiling  issue with c program utilizing quirc library?

### ISSUE THREAD

**Issue by ercjethava** [dlbeer/quirc#53]
For  compiling c code which utilizing function defined in "dbgutil.h".Like
void dump_data(const struct quirc_data *data);
void dump_cells(const struct quirc_code *code);
int load_jpeg(struct quirc *q, const char *filename);
int check_if_png(const char *filename);
int load_png(struct quirc *q, const char *filename);

I have to include dbgutil.c file in my compiling process.Like

gcc test.c dbgutil.c -o test -lquirc -lpng -ljpeg (compiling test.c code)

otherwise it throwing error related to these functions defined in dbgutil.h file.

Is these function is not part of libquirc.so librray?

**Comment by kAworu** [comment]
Hello @ercjethava,

To answer your question: No they are not part of libquirc.

From the README (emphasis mine):
> It is small and **easily embeddable**, with no dependencies other than standard C functions

libjpng, libjpeg, stdio, and filesystem stuff are not classified as "easily embeddable".

**Comment by ercjethava** [comment]
OK thanks.So every time I am using quirc library I have to include dbgutil.c file in my compiling process. @kAworu
