### ISSUE TITLE
sizeof() a dynamically allocated array is always 1?

### ISSUE THREAD

**Issue by tianli** [dlbeer/quirc#54]
It seems both q->image and q-> pixels are pointers to dynamically allocated arrays. The sizeof() operator have no way of knowing the actual size of the malloc array. This expression will always be true and the first branch will always taken, which makes the if statement useless.
https://github.com/dlbeer/quirc/blob/307473dbcab5e6c9654944c034b2426f46ac509f/lib/identify.c#L1079

**Comment by dlbeer** [comment]
tianli <notifications@github.com> writes:
> It seems both q->image and q-> pixels are pointers to dynamically allocated arrays. The sizeof() operator have no way of knowing the actual size of the malloc array. This expression will always be true and the first branch will always taken, which makes the if statement useless.
> https://github.com/dlbeer/quirc/blob/307473dbcab5e6c9654944c034b2426f46ac509f/lib/identify.c#L1079

The two sizeof operators in that condition are acting on the
dereferenced type, not the pointer. It's equivalent to:

    sizeof(uint8_t) == sizeof(quirc_pixel_t)

This can be determined at compile-time but is not necessarily the same
in all builds.

Cheers,
Daniel

--
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by tianli** [comment]
OK, got it. So this is to make sure the two types match, not the sizes of the buffer match. Thanks!

**Comment by dlbeer** [comment]
tianli <notifications@github.com> writes:
>    OK, got it. So this is to make sure the two types match, not the sizes of
>    the buffer match. Thanks!

Correct -- the type of quirc_pixel_t depends on QUIRC_MAX_REGIONS (see
lib/quirc_internal.h).

--
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B
