### ISSUE TITLE
Failing to detect a QR code with background

### ISSUE THREAD

**Issue by lifugang** [dlbeer/quirc#58]
Dear dlbeer,
I find, quirc can not detect the qr code like this image.

![image](https://user-images.githubusercontent.com/24383910/60503148-b341dc00-9cf1-11e9-8d87-b3ea26149d4c.png)

**Comment by dlbeer** [comment]
lifugang <notifications@github.com> writes:
>    Dear dlbeer,
>    I find, quirc can not detect the qr code like this image.
>
>    [1]image
>
>    —
>    You are receiving this because you are subscribed to this thread.
>    Reply to this email directly, [2]view it on GitHub, or [3]mute the thread.

That's not a valid QR code -- the spec requires a one-cell border around
the outside of the code. It's unlikely that the finder will detect the
capstones without it.

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by lifugang** [comment]
> lifugang <notifications@github.com> writes:
>     Dear dlbeer,
>     I find, quirc can not detect the qr code like this image.
> 
>     [1]image
> 
>     —
>     You are receiving this because you are subscribed to this thread.
>     Reply to this email directly, [2]view it on GitHub, or [3]mute the thread.
> That's not a valid QR code -- the spec requires a one-cell border around
> the outside of the code. It's unlikely that the finder will detect the
> capstones without it.
> 
> Cheers,
> Daniel
> …

Thank you， you mean the border color around the outside of the code must be white?

**Comment by dlbeer** [comment]
Yes, that's correct.
