### ISSUE TITLE
Coverity complaining about improper use of negative value

### ISSUE THREAD

**Issue by snake66** [dlbeer/quirc#6]
This issue is really a false positive in the Coverity static analyzer, but proposing the following patch to make it happy:

```diff
diff --git a/functional/libquirc/lib/identify.c b/functional/libquirc/lib/identify.c
index 3651ff2..8d4a511 100644
--- a/functional/libquirc/lib/identify.c
+++ b/functional/libquirc/lib/identify.c
@@ -1011,7 +1011,7 @@ static void test_neighbours(struct quirc *q, int i,
                        }
                }
 
-       if (best_h < 0)
+       if (best_h < 0 || best_v < 0)
                return;
 
        record_qr_grid(q, best_h, i, best_v);
```

It complains that `best_v` could possibly be passed to `record_qr_grid` while negative, where it will be used as an index into an array. Looking at how `test_neighbours` is called, I think that is not correct, but I think the fix is not too intrusive, so I hope it's acceptable to you.

**Comment by dlbeer** [comment]
Commit https://github.com/dlbeer/quirc/commit/8d0eb68255c259d5c2688fa5c7acb2162f5da180
