### ISSUE TITLE
OTSU thresholding fails when QR code is computer generated values

### ISSUE THREAD

**Issue by sushshring** [dlbeer/quirc#60]
If a QR code is computer generated and has purely 0x00 and 0xff values, the OTSU thresholding fails. This could be due to two things, fixing any of which seems to solve the issue:
- In the `otsu()` method, the max check is incorrectly implemented at line 219 (identify.c).
```
if (variance > max) {
	threshold = i;
	max = variance;
}
```
The check should be `variance >= max`, specifically as per the wikipedia on otsu thresholding.
- The second reason this fails is that the check at line 1083 (identify.c) `*dest++ = (value < threshold) ? QUIRC_PIXEL_BLACK : QUIRC_PIXEL_WHITE;` checks for a strictly less than value. This means that if the threshold is zero, the entire image appears white, which shouldn't be the case for an image that has no internal gray noise and is purely black and white (already thresholded).

The issue goes away after fixing the first bullet here and the threshold gets set to `0xfe`, as should be. However, I don't know enough about the thresholding to give an educated answer about which is the correct method to solve this issue.

**Comment by dlbeer** [comment]
@claudiofelber Any suggestions here? The first option seems fine to me, but I've only quickly skimmed the description of Otsu's method.

**Comment by kAworu** [comment]
+1 for `variance >= max`

**Comment by dlbeer** [comment]
On Mon, Sep 02, 2019 at 08:49:47AM -0700, Alexandre Perrin wrote:
> +1 for `variance >= max`

If anyone wants to go ahead and change and test this, I'm happy to merge
it.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B
