### ISSUE TITLE
Is it possible to decode QR code using FHD frame (1920X1080) ?

### ISSUE THREAD

**Issue by nickwhsu** [dlbeer/quirc#63]
Hi ,

Thanks for this qr code decoding library. 
I'm trying quirc-scanner example, it can work with VGA frame.
But it cant work using quirc_resize(qr, 1920, 1080), will cause segmentation fault. 
Can we use others resolution besides VGA ?

Thanks.

**Comment by kAworu** [comment]
Hell @nickwhsu,

A segfault is strange, can you provide the image triggering the problem?

To answer your question: try building with `CFLAGS="-DQUIRC_MAX_REGIONS=65534" make`. Then, quirc should be able to decode your images (I'm decoding [2560x1440 images](https://github.com/kAworu/node-quirc/blob/master/test/data/big_image_with_two_qrcodes.jpeg) without issue).

**Comment by nickwhsu** [comment]
It can work with CFLAGS="-DQUIRC_MAX_REGIONS=65534" make .
Thanks.

**Comment by dlbeer** [comment]
On Wed, Oct 23, 2019 at 03:41:15AM -0700, nickhsu wrote:
> It can work with CFLAGS="-DQUIRC_MAX_REGIONS=65534" make .

Good to hear, but if you have time, would it be possible to show us what
caused the segmentation fault?

It shouldn't crash even under the circumstances you described -- if it
does, that's a bug.

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by nickwhsu** [comment]
I didn't modify the static variable(video_width/video_height)  camera open  in 
scanner.c ,  only modify quirc_resize(qr,1980,1080), than run the quirc-scanner example. 
That should be a coding mistake.
Thanks.

**Comment by dlbeer** [comment]
On Thu, Oct 24, 2019 at 07:46:05PM -0700, nickhsu wrote:
> I didn't modify the static variable(video_width/video_height)  camera open  in 
> scanner.c ,  only modify quirc_resize(qr,1980,1080), than run the quirc-scanner example. 
> That should be a coding mistake.
> Thanks.

Ok, that would explain it -- thanks!

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B
