### ISSUE TITLE
how to extract luma channel from a 4:2:0 YUV image?

### ISSUE THREAD

**Issue by nickwhsu** [dlbeer/quirc#64]
Hi 
I'm working on porting the quirc library on embedded system, and try to  refer the quirc-scanner example to scan qrcode. 
However my device support the video format is YUV420 , 
Is it suitable for scanning qrcode ? and how to extract luma channel from yuv420 image?
I 'm not have much experience on qrcode scan , but if any suggestions would be helpful.

Thanks.
Nick

**Comment by dlbeer** [comment]
On Mon, Nov 11, 2019 at 02:31:24AM -0800, nickhsu wrote:
> I'm working on porting the quirc library on embedded system, and try to  refer the quirc-scanner example to scan qrcode. 
> However my device support the video format is YUV420 , 
> Is it suitable for scanning qrcode ? and how to extract luma channel from yuv420 image?
> I 'm not have much experience on qrcode scan , but if any suggestions would be helpful.

Yes, that should be fine. You will only need the Y channel. I'm not sure
how YUV420 is stored, but it may be that you can reuse the
yuyv_to_luma() function from the demo program, or modify it slightly to
get what you need.

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B
