### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by SpaceIm** [dlbeer/quirc#67]
Hi, I'm packaging this lib for conan: https://github.com/conan-io/conan-center-index/pull/944

Would it be possible to create a new release as you did 3 years ago for homebrew?

**Comment by dlbeer** [comment]
On Tue, Feb 25, 2020 at 04:21:09AM -0800, SpaceIm wrote:
> Hi, I'm packaging this lib for conan: https://github.com/conan-io/conan-center-index/pull/944
> 
> Would it be possible to create a new release as you did 3 years ago for homebrew?

Sure can. Is the current master ok to use, or are there any changes you
need for packaging?

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by SpaceIm** [comment]
The last commit on master is fine for me. Thanks a lot.

**Comment by dlbeer** [comment]
On Tue, Feb 25, 2020 at 04:21:09AM -0800, SpaceIm wrote:
> Hi, I'm packaging this lib for conan: https://github.com/conan-io/conan-center-index/pull/944
> 
> Would it be possible to create a new release as you did 3 years ago for homebrew?

I've tagged the current master as v1.1.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by SpaceIm** [comment]
Great, thanks !
