### ISSUE TITLE
Could not decode codes generated using qrcodejs

### ISSUE THREAD

**Issue by WoodyGuo** [dlbeer/quirc#70]
We are using [qrcodejs](https://github.com/davidshimjs/qrcodejs) to generate qr codes on our server, and the problem is that, the codes generated are not decoded properly.

Open the `index.html` from qrcodejs with Chrome or any browser, save the qr code to a file and `inspect` will tell you that "0 QR-codes found".

I did find out a workaround to this issue: adding a border to the generated code as follows:

```c++
    auto mat = cv::imread("qrcode.png", cv::IMREAD_GRAYSCALE);
    auto size = mat.size();
    cv::Mat vm(5, size.width, mat.type(), 255);
    cv::vconcat(vm, mat, mat);
    cv::vconcat(mat, vm, mat);
    size = mat.size();
    cv::Mat hm(size.height, 5, mat.type(), 255);
    cv::hconcat(hm, mat, mat);
    cv::hconcat(mat, hm, mat);
```
Then I'm able to decode the `mat` properly.

Any ideas why the border is mandatory for it to be decoded properly?

**Comment by dlbeer** [comment]
On Fri, Mar 27, 2020 at 07:05:50PM -0700, Woody Guo wrote:
> We are using [qrcodejs](https://github.com/davidshimjs/qrcodejs) to generate qr codes on our server, and the problem is that, the codes generated are not decoded properly.
> 
> Open the `index.html` from qrcodejs with Chrome or any browser, save the qr code to a file and `inspect` will tell you that "0 QR-codes found".
> 
> I did find out a workaround to this issue: adding a border to the generated code as follows:
> 
> ```c++
>     auto mat = cv::imread("qrcode.png", cv::IMREAD_GRAYSCALE);
>     auto size = mat.size();
>     cv::Mat vm(5, size.width, mat.type(), 255);
>     cv::vconcat(vm, mat, mat);
>     cv::vconcat(mat, vm, mat);
>     size = mat.size();
>     cv::Mat hm(size.height, 5, mat.type(), 255);
>     cv::hconcat(hm, mat, mat);
>     cv::hconcat(mat, hm, mat);
> ```
> Then I'm able to decode the `mat` properly.
> 
> Any ideas why the border is mandatory for it to be decoded properly?

Hi Woody,

A one-cell border is required by the QR code specification. quirc
assumes the existence of the border when trying to detect capstones, as
it looks for transitions between black and white.

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by WoodyGuo** [comment]
Thanks Daniel for your quick response!

I was just not aware of this requirement.

**Comment by kAworu** [comment]
The quiet zone is easy to overlook. I believe the spec goes further and require 4 modules for the quiet zone, see https://www.qrcode.com/en/howto/code.html. In practice, one module is usually enough for most decoder.
