### ISSUE TITLE
3 out of 4 QR codes in this image give ECC failures

### ISSUE THREAD

**Issue by JaapHaitsma** [dlbeer/quirc#72]
![qr-codes-4](https://user-images.githubusercontent.com/905295/80010537-8afdb680-8498-11ea-8a36-3d2cf0032a5e.jpg)

This webapp https://qrcodereader.glitch.me/ I wrote using https://github.com/cozmo/jsQR when run on a phone can find all 4 by just showing the image on the screen of a computer and then having the phone capture it. 

NOTE I'm porting quirc to WASM. I already got the the compilation to WASM working and its running a lot faster than jsQR. On my PC it runs a scan within 1-2ms. Will share that when I cleaned it up a bit

**Comment by dlbeer** [comment]
On Wed, Apr 22, 2020 at 10:03:14AM -0700, JaapHaitsma wrote:
> ![qr-codes-4](https://user-images.githubusercontent.com/905295/80010537-8afdb680-8498-11ea-8a36-3d2cf0032a5e.jpg)
> 
> This webapp https://qrcodereader.glitch.me/ I wrote using https://github.com/cozmo/jsQR when run on a phone can find all 4 by just showing the image on the screen of a computer and then having the phone capture it. 
> 
> NOTE I'm porting quirc to WASM. I already got the the compilation to WASM working and its running a lot faster than jsQR. On my PC it runs a scan within 1-2ms. Will share that when I cleaned it up a bit
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dlbeer/quirc/issues/72

All the capstones in this image were found, but they were matched up
incorrectly in all but one case. You might be able to improve things by
playing around with test_neighbours() and test_grouping() in
lib/identify.c.

Not sure if I can think of any specific changes that would help, but let
me know if you come up with any improvements.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by JaapHaitsma** [comment]
OK thanks will have a look.

**Comment by JaapHaitsma** [comment]
@dlbeer I am starting to understand the the test_neighbours and test_grouping() functions but I have some problems with the perspective mapping functions. Can you point me what the math is behind this array c[QUIRC_PERSPECTIVE_PARAMS]. It has 8 members. I expected it to have 6 members because I think you are trying to undo an affine transform. There are also the constant 7 and 3.5 in the code. What do these constants represent? I would appreciate some explanation or a good pointer to stuff to read. Thanks

**Comment by dlbeer** [comment]
On Sun, May 17, 2020 at 01:54:20PM -0700, JaapHaitsma wrote:
> @dlbeer I am starting to understand the the test_neighbours and test_grouping() functions but I have some problems with the perspective mapping functions. Can you point me what the math is behind this array c[QUIRC_PERSPECTIVE_PARAMS]. It has 8 members. I expected it to have 6 members because I think you are trying to undo an affine transform. There are also the constant 7 and 3.5 in the code. What do these constants represent? I would appreciate some explanation or a good pointer to stuff to read. Thanks

Not quite -- it's undoing a projective transform. Any combination of
four corners in the image defines a transform, so there are 8
parameters.

Those 3.5/7 constants are used to try to establish a transform for an
entire QR code based only on a single capstone, and then try to use it
to find the middle of the capstone. The capstone is 7 cells along and
3.5 cells in should be the centre of the 3x3 blob.

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by JaapHaitsma** [comment]
The fix for this issue is in https://github.com/dlbeer/quirc/pull/109
