### ISSUE TITLE
QR code standards/variants supported?

### ISSUE THREAD

**Issue by ceztko** [dlbeer/quirc#86]
For software selection purposes, can you be a little bit more specific in the README.md about what QR code standards/variants the library is supposed to support?

**Comment by dlbeer** [comment]
On Mon, Aug 31, 2020 at 02:32:53AM -0700, Francesco Pretto wrote:
> For software selection purposes, can you be a little bit more specific
> in the README.md about what QR code standards/variants the library is
> supposed to support?

Hi Francesco,

It supports all versions (1--40) of standard QR codes. Is there
something else you had in mind that it might not support?

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by mgoutelle** [comment]
Hello,
Would you be willing to add support for micro QR-code?
https://www.qrcode.com/en/codes/microqr.html

**Comment by kuangguo** [comment]
> 在 2020 年 8 月 31 日星期一上午 02:32:53 -0700，Francesco Pretto 写道：出于软件选择的目的，您能否在 README.md 中更具体地说明库应该使用哪些 QR 码标准/变体支持？
> 嗨 Francesco，它支持标准 QR 码的所有版本 (1--40)。您是否还有其他可能不支持的想法？干杯，丹尼尔
> [……](#)
> -- Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/ PGP: BA6E 0B26 1F89 246C E3F3 C910 1E58 C43A 160A 553B

Can support qr code Model1?
